name: Docker Build & Deploy to EC2

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때 자동 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # (1) 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # (2) Docker Hub 로그인
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # (3) Docker Build (Dockerfile 기반)
      - name: Build Docker Image
        run: |
          docker build -t myrepo/myapp:latest .

      # (4) Docker Hub에 Push
      - name: Push Docker Image
        run: |
          docker push myrepo/myapp:latest

      # (5) SSH로 EC2 접속 → 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull myrepo/myapp:latest
            docker stop myapp || true
            docker rm myapp || true
            # 80:8080 으로 매핑 (Spring Boot의 8080)
            docker run -d --name myapp -p 80:8080 myrepo/myapp:latest



