name: Docker Build & Deploy to EC2

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때 자동 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # (1) 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v3

      # (2) Docker Hub 로그인
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # (3) Docker Build (Dockerfile 기반)
      - name: Build Docker Image
        run: |
          docker build -t mefin9291/dcmall:latest .

      # (4) Docker Hub에 Push
      - name: Push Docker Image
        run: |
          docker push mefin9291/dcmall:latest

      # (5) SSH로 EC2 접속 → 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u "xxeldoradornrmf@gmail.com" -p "18tjq!~_(docker)"
            docker pull mefin9291/dcmall:latest
            docker stop dcmall || true
            docker rm dcmall || true
            # 80:8080 으로 매핑 (Spring Boot의 8080)
            docker run -d --name dcmall -p 80:8080 \
            -v /dcmallkey/application.properties:/app/config/application.properties \
            -e JAVA_OPTS="-Xms256m -Xmx512m" \
            mefin9291/dcmall:latest



